.gitignore, README.md, builders.json, e2e/generic-dev-server-schema.spec.ts, index.ts, merge-schemes.ts, package-lock.json, package.json, src/generic/dev-server/index.ts, src/generic/dev-server/schema.d.ts, src/generic/dev-server/schema.ext.json, src/generic/generic-webpack-builder.spec.ts, src/generic/generic-webpack-builder.ts
This PR is based upon the feedback on https://github.com/meltedspark/angular-cli-builders/pull/6. It creates a new generic dev server where if the build target is a browserBuilder then it uses that builder's public buildWebpackConfig() method to generate the webpack config.
=> Added generic dev server 

packages/jest/src/custom-config.resolver.spec.ts, packages/jest/src/custom-config.resolver.ts, packages/jest/src/default-config.resolver.spec.ts, packages/jest/src/default-config.resolver.ts, packages/jest/src/jest-configuration-builder.spec.ts, packages/jest/src/jest-configuration-builder.ts, packages/jest/src/jest.builder.ts, packages/jest/src/options-converter.spec.ts, packages/jest/src/options-converter.ts
Addresses issue: https://github.com/meltedspark/angular-builders/issues/84
In this effort I had to restructure the code to use instance methods instead of static ones to get the logger down to the custom config resolver instance.
=> adds warning log when custom configuration is not found. 

package.json, yarn.lock
Remove @angular/cli from devDependencies (to avoid conflicts in @angular-devkit versions)
=> fix greenkeeper failing builds

packages/jest/src/schema.json
According to the docs, https://jestjs.io/docs/en/configuration.html#collectcoveragefrom-array, this item is an array and not a string
=> fix(jest): add correct schema typing for collectCoverageFrom

packages/custom-webpack/.yarnignore, packages/dev-server/.yarnignore, packages/jest/.yarnignore, packages/timestamp/.yarnignore
This fixes #207
This is a replacement for #208. We have decided not to use `files` since it doesn't work properly with `yarn` at this time.
=> chore(package): include subdirectories from typings for package

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, package.json, packages/custom-webpack/README.md, packages/jest/README.md, packages/jest/examples/multiple-apps/projects/my-shared-library/README.md, packages/timestamp/README.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
```
[ ] Yes
[x] No
```
=> style: automatic standards for markdown files

packages/custom-webpack/README.md, packages/custom-webpack/examples/full-cycle-app/angular.json, packages/custom-webpack/examples/full-cycle-app/extra-webpack.config.ts, packages/custom-webpack/package.json, packages/custom-webpack/src/custom-webpack-builder.spec.ts, packages/custom-webpack/src/custom-webpack-builder.ts
Closes #16 
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(custom-webpack): support Webpack config written in TS

packages/custom-webpack/README.md, packages/custom-webpack/examples/full-cycle-app/angular.json, packages/custom-webpack/examples/full-cycle-app/func-webpack.config.ts, packages/custom-webpack/src/custom-webpack-builder.ts
```
[x] Bugfix
[ ] Feature
```
I noticed that TypeScript support was recently added, so I tried it out. It didn't seem to work with my config, and I am pretty sure it's because I am exporting a function rather than an object. The code that was added to support TypeScript only seems to test for objects before my PR.
Also, apologies, I couldn't find any tests to modify to account for my fix. You'll have to point them out to me if they exist.
Exported function works with …
=> fix(custom-webpack): support exporting function in config written in TS

packages/custom-webpack/README.md, packages/jest/README.md, packages/jest/examples/multiple-apps/package.json, packages/jest/examples/simple-app/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: minor fixes

packages/custom-webpack/README.md, packages/custom-webpack/examples/full-cycle-app/func-webpack.config.ts, packages/custom-webpack/src/common.ts, packages/custom-webpack/src/custom-webpack-builder.spec.ts, packages/custom-webpack/src/custom-webpack-builder.ts
```
[ ] Bugfix
[x] Feature
```
Custom webpack configuration functions are not able to access the target and therefore are not able to vary their behavior base on the invoked build.
Passes TargetOptions to the Custom Webpack Config function per Issue @683
```
[ ] Yes
[X] No
```
=> resolves #683

packages/custom-webpack/src/index.ts
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
I need to use only the factory for modification of `webpack` configuration. But the factory is not exported.
The factory is exported
```
[ ] Yes
[x] No
```
=> feat(custom-webpack): export common

packages/custom-webpack/README.md, packages/custom-webpack/builders.json, packages/custom-webpack/src/browser/index.ts, packages/custom-webpack/src/dev-server/index.ts, packages/custom-webpack/src/extract-i18n/index.ts, packages/custom-webpack/src/extract-i18n/schema.ext.json, packages/custom-webpack/src/generic-browser-builder.ts, packages/custom-webpack/src/index.ts, packages/custom-webpack/src/karma/index.ts, packages/custom-webpack/src/schemes.ts, packages/custom-webpack/src/server/index.ts, packages/custom-webpack/src/transform-factories.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: closes #659 
A new `extract-i18n` builder is available in `@angular-builders/custom-webpack` thus supporting custom extraction flows.
```
[ ] Yes
[x] No
```
=> feat(custom-webpack): add extract-i18n builder

packages/jest/src/jest-config/global-mocks.ts
```
[X] Bugfix
[ ] Feature
```
Currently the Jest builder is adding a mock for local storage and session storage. But this mock has missing features like the `length` property or a `keys` method.
This breaks unit tests which are using the localForage library because it uses the `length` property and `keys` method.
We remove the mock altogether because as the builder is requiring Jest >= 26 which requires the newest jsdom version (16) which itself has …
=> fix(jest): remove local storage mock

packages/custom-webpack/examples/full-cycle-app/angular.json, packages/custom-webpack/examples/sanity-app/angular.json, packages/jest/examples/multiple-apps/angular.json, packages/jest/examples/simple-app/angular.json, packages/timestamp/example/angular.json, scripts/run-ci.sh
```
[x] Bugfix
[x] Feature
```
Some pull requests pipeline fail because the version of Chrome in Xenius is different of the version of Chrome that the protractor's `webdriver-manager` can load. In this pull request, I make sure that the right `webdriver-manager` is download before e2e tests running
Pull request:  #879 #880  #881
```
[ ] Yes
[x] No
```
Impired by propositions in [this](https://github.com/angular/webdriver-manager/issues/269) issue
=> Fix e2e test

MIGRATION.MD, package.json, packages/custom-webpack/README.md, packages/custom-webpack/e2e/custom-webpack-config-schema.ts, packages/custom-webpack/package.json, packages/custom-webpack/src/custom-webpack-builder-config.ts, packages/custom-webpack/src/custom-webpack-builder.spec.ts, packages/custom-webpack/src/custom-webpack-builder.ts, packages/custom-webpack/src/schema.ext.json, packages/custom-webpack/src/webpack-config-merger.spec.ts, packages/custom-webpack/src/webpack-config-merger.ts
```
[ ] Bugfix
[x] Feature
```
- Custom webpack builder uses `webpack-merge@4`, with `smart` strategy as a default. 
- The configuration field is called `mergeStrategies`
- Custom webpack builder uses `webpack-merge@5`, `mergeWithRules` method, with some predefined configuration as a default. Tried to keep it as close as possible to the `smart` strategy.
- The configuration field is called `mergeRules`
```
[x] Yes
[ ] No
```
The migration path is …
=> Update webpack merge

packages/custom-webpack/package.json, packages/custom-webpack/src/webpack-config-merger.spec.ts
```
[x] Bugfix
[ ] Feature
```
Loaders merge might fail because one of Angular loaders is defined as a string and not as an object. More info [here](https://github.com/just-jeb/angular-builders/issues/908#issuecomment-747424538) and [here](https://github.com/survivejs/webpack-merge/issues/170#issue-770082482).
Builder update to a newer version of webpack-merge in which this issue is fixed.
```
[ ] Yes
[x] No
```
=> fix: allow merging loader name with loader object

.github/workflows/ci.yml
```
[ ] Bugfix
[ ] Feature
```
Fork PR builds [fail](https://github.com/just-jeb/angular-builders/pull/879#issuecomment-763161710) because of missing token.
Fork PR builds use the checkout action without the token.
```
[ ] Yes
[x] No
```
=> ci: allow checkout without the GH token (for forks)

packages/custom-webpack/README.md, packages/custom-webpack/examples/full-cycle-app/angular.json, packages/custom-webpack/examples/full-cycle-app/e2e/protractor.conf.js, packages/custom-webpack/examples/full-cycle-app/e2e/src/app.e2e-spec-itwcw.ts, packages/custom-webpack/examples/full-cycle-app/e2e/src/app.e2e-spec-prod.ts, packages/custom-webpack/examples/full-cycle-app/e2e/src/app.e2e-spec.ts, packages/custom-webpack/examples/full-cycle-app/e2e/src/app.po.ts, packages/custom-webpack/examples/full-cycle-app/extra-webpack.config.ts, packages/custom-webpack/examples/full-cycle-app/func-webpack.config.ts, packages/custom-webpack/examples/full-cycle-app/src/app/app.component.html, packages/custom-webpack/examples/full-cycle-app/src/app/app.component.scss, packages/custom-webpack/examples/full-cycle-app/src/app/app.component.spec.ts, packages/custom-webpack/examples/full-cycle-app/src/app/app.component.ts, packages/custom-webpack/examples/full-cycle-app/src/app/app.module.ts, packages/custom-webpack/examples/full-cycle-app/src/main.ts, packages/custom-webpack/examples/full-cycle-app/tsconfig.base.json, packages/custom-webpack/examples/sanity-app/angular.json, packages/custom-webpack/package.json, packages/custom-webpack/src/custom-webpack-builder.ts, packages/custom-webpack/src/custom-webpack-schema.ts, packages/custom-webpack/src/transform-factories.ts, packages/custom-webpack/src/utils.ts
```
[x] Bugfix
[ ] Feature
```
The application's `tsconfig` is ignore. Accordingly, `indexTransform` and `customWebpackConfig` cannot use project configuration for custom modules for example
Issue Number: #607 #749 
The application's `tsconfig` is now use. `indexTransform` and `customWebpackConfig` can now use all the application resources.
```
[ ] Yes
[x] No
```
=> Use application tsconfig file for indexTransform and customWebpackConfig

packages/jest/package.json, packages/jest/src/jest-config/setup.ts
```
[ ] Bugfix
[ ] Feature
```
With the latest `jest-preset-angular` my console logs and the CI logs are polluted with:
and as the dependency is defined as `^8.3.2` I cannot avoid the lock file to be refreshed with `8.4.0`
Thanks in advance
=> fix(jest): sync latest jest-preset-angular

packages/custom-webpack/e2e/custom-webpack-config-schema.ts, packages/custom-webpack/src/schema.ext.json
```
[x] Bugfix
[ ] Feature
```
At the moment if someone uses this with the latest versions of [Nx](https://nx.dev) and does not specify a `webpack.config.js` the build fails because it requires one.
The reason is how the defaults are being interpreted by the Angular CLI vs Nx schema parser. Right now the `custom-webpack` browser schema defines `customWebpackConfig` to be of type `object` but assigns a boolean value as the default. The Angular CLI is less strict in that …
=> fix(custom-webpack): specify possible types of customWebpackConfig values

packages/jest/README.md
The documentation states that jest 26 is required. However, the package.json requires >= 27
Also, `ng update @angular-builders/jest` updates jest to 27 as well.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs: update required jest version to 27

packages/custom-webpack/src/custom-webpack-builder.spec.ts, packages/custom-webpack/src/custom-webpack-builder.ts, packages/custom-webpack/src/transform-factories.spec.ts, packages/custom-webpack/src/transform-factories.ts, packages/custom-webpack/src/utils.ts
```
[x] Bugfix
[ ] Feature
```
Closes #1037 
Multiple `ts-node` registration attempts result in a warning, only first is really registered.
```
[ ] Yes
[x] No
```
Initially issue was introduced with PR #1035. The original PR aimed to solve `ts-node` double registration with the same tsconfig and the base assumption was that it would never be called with two different tsconfigs.  
That assumption, however, turned to be wrong - in #1037 we see that the usage of …
=> fix(custom-webpack): warn about multiple tsconfigs for custom config

.github/workflows/ci.yml
```
[ ] Bugfix
[ ] Feature
```
`node_modules` directories are cached .  
This bypasses more intelligent caching packaged with `npm` or `yarn`, and can cause issues with Cypress not downloading the Cypress binary on `yarn install`.
`~/.cache` directory is cached, it's a default directory for both Cyrpess and Yarn.
```
[ ] Yes
[x] No
```
=> ci: cache Yarn and Cypress

package.json, yarn.lock
```
[ ] Bugfix
[ ] Feature
```
Yarn `resolutions` are used for all the packages 
Yarn `resolutions` are used just for the packages that need it (`@cypress/schematic`)
```
[ ] Yes
[x] No
```
=> chore: use resolutions for @cypress/schematic only

renovate.json
```
[ ] Bugfix
[ ] Feature
```
Sometimes (primarily on Angular CLI deps updates) the `yarn.lock` becomes bloated and causes the monorepo to contain multiple Angular versions, although according to the version range overlap there should be only one.
`yarn-deduplicate` is run after each dependency upgrade, thus minimizing the amount of different versions in monorepo
```
[ ] Yes
[x] No
```
=> ci(renovate): run yarn-deduplicate on renovate PRs

packages/jest/scripts/ci.sh, packages/jest/src/schema.json
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1314
```
[ ] Yes
[x] No
```
=> feat(jest): support shard CLI options (#1314)

MIGRATION.MD, examples/jest/simple-app/src/app/app.component.spec.ts, packages/jest/README.md, packages/jest/src/schema.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Global mocks enabled by default are `["getComputedStyle", "doctype", "styleTransform", "matchMedia"]`
Global mocks enabled by default are `["styleTransform", "matchMedia"]`
```
[x] Yes
[ ] No
```
Refer to MIGRATION.MD For instructions
Closes #1369, #1333
=> chore(jest): update default mocks

examples/jest/multiple-apps/tsconfig.spec.json, packages/jest/src/default-config.resolver.spec.ts, packages/jest/src/default-config.resolver.ts
Option `tsConfig` in angular.json is ignored. `tsconfig.spec.json` [seems to be loaded from the CWD](https://github.com/just-jeb/angular-builders/issues/1408#issuecomment-1609794674) instead of the project root.
Issue Number: #1408 
Eventually yes, if suddenly the path to tsconfig is configured correctly.
Followed the docs of `jest-preset-angular` to override/extend the transform config.
https://thymikee.github.io/jest-preset-angular/docs/getting-started/presets/#advanced
Tested it locally by building and copying over the dist folder to node_modules/@angular-builders/jest.
=> fix(jest): set path to tsconfig correctly

packages/jest/README.md
```
[ ] Bugfix
[ ] Feature
[ X] Documentation content changes
```
Currently I was upgrading  an older version of @angular-builders/jest@15  and got confused by the docs (on tag `15.x.x`), saying that it needs Angular 14, when the peer dependencies says that it needs Angular v15.
https://github.com/just-jeb/angular-builders/blob/a3bfedc81d3422f810225245cc048f0373a05e65/packages/jest/package.json#L44-L46
The `README` says the correct Angular v15 version that it needs.
```
[ ] Yes
[X] No
```
=> docs: fix angular version typo on 15.x.x

examples/custom-esbuild/sanity-esbuild-app-esm/angular.json, examples/custom-esbuild/sanity-esbuild-app-esm/esbuild/define-text-by-option-plugin.cjs, examples/custom-esbuild/sanity-esbuild-app-esm/esbuild/define-text-by-option-plugin.js, examples/custom-esbuild/sanity-esbuild-app-esm/esbuild/define-text-by-option-plugin.ts, examples/custom-esbuild/sanity-esbuild-app-esm/src/app/app.component.html, examples/custom-esbuild/sanity-esbuild-app-esm/src/app/app.component.ts, examples/custom-esbuild/sanity-esbuild-app/angular.json, examples/custom-esbuild/sanity-esbuild-app/esbuild/define-text-by-option-plugin.js, examples/custom-esbuild/sanity-esbuild-app/esbuild/define-text-by-option-plugin.mjs, examples/custom-esbuild/sanity-esbuild-app/src/app/app.component.html, examples/custom-esbuild/sanity-esbuild-app/src/app/app.component.ts, packages/custom-esbuild/README.md, packages/custom-esbuild/package.json, packages/custom-esbuild/src/application/schema.ext.json, packages/custom-esbuild/src/custom-esbuild-schema.ts, packages/custom-esbuild/src/load-plugin.spec.ts, packages/custom-esbuild/src/load-plugins.ts
```
[ ] Bugfix
[x] Feature
```
esbuild plugin options cannot be provided
Issue Number: #1661 
esbuild plugin options can be provided using 
```json
{
"plugins": ["without-options",  { "path" : "with-options", "options" : {}}]
}
```
```
[ ] Yes
[x] No
```
=> feat(custom-esbuild): add support for plugin configuration
