just-jeb/angular-builders

README.md
package-lock.json
package.json
src/custom-webpack/server/schema.json

Fix server schema

---

.gitignore
README.md
e2e/custom-webpack-browser-schema.spec.ts
e2e/custom-webpack-server-schema.spec.ts
src/custom-webpack/browser/index.ts
src/custom-webpack/browser/schema.d.ts
src/custom-webpack/browser/schema.ext.json
src/custom-webpack/server/index.ts
src/custom-webpack/server/schema.d.ts
src/custom-webpack/server/schema.ext.json

Added option for merge strategies

---

packages/custom-webpack/README.md
packages/custom-webpack/package.json
packages/custom-webpack/webpack-config-merger.spec.ts
packages/custom-webpack/webpack-config-merger.ts

Support loaders merge

---

packages/jest/src/options-converter.spec.ts
packages/jest/src/options-converter.ts

fix(jest): enclose with quotes only options that contain whitespaces

---

packages/custom-webpack/README.md
packages/custom-webpack/src/webpack-config-merger.spec.ts
packages/custom-webpack/src/webpack-config-merger.ts

Merge plugins

---

packages/jest/src/options-converter.spec.ts
packages/jest/src/options-converter.ts

fix(jest): Handle properly options enclosed with quotes

---

package.json
yarn.lock

Greenkeeper/ts jest 23.10.3

---

packages/custom-webpack/README.md
packages/custom-webpack/builders.json
packages/custom-webpack/e2e/custom-webpack-karma-schema.spec.ts
packages/custom-webpack/src/browser/index.ts
packages/custom-webpack/src/karma/index.ts
packages/custom-webpack/src/karma/karma-builder.spec.ts
packages/custom-webpack/src/karma/schema.d.ts
packages/custom-webpack/src/karma/schema.ext.json
packages/custom-webpack/src/schemes.ts

feat(custom-webpack): support karma builder

---

packages/jest/examples/simple-app/package.json
packages/jest/examples/simple-app/yarn.lock
packages/jest/package.json
packages/jest/scripts/ci.sh
packages/jest/src/options-converter.spec.ts
packages/jest/src/options-converter.ts
packages/jest/src/schema.json
packages/jest/src/schema.ts

fix(jest): fix Jest builder to properly support array options

---

packages/custom-webpack/README.md
packages/custom-webpack/examples/append-webpack-plugins/angular.json
packages/custom-webpack/examples/append-webpack-plugins/func-webpack.config.js
packages/custom-webpack/scripts/ci.sh
packages/custom-webpack/src/browser/index.ts
packages/custom-webpack/src/custom-webpack-builder.spec.ts
packages/custom-webpack/src/custom-webpack-builder.ts
packages/custom-webpack/src/custom-webpack-schema.ts
packages/custom-webpack/src/karma/index.ts
packages/custom-webpack/src/karma/karma-builder.spec.ts
packages/custom-webpack/src/server/index.ts

This is a continuation of #152 and fixes #135 and #257 
See README for example usage.

feat(custom-webpack): Export function in webpack configuration

---

packages/jest/src/options-converter.spec.ts
packages/jest/src/options-converter.ts
packages/jest/src/schema.ts

Accept numerical arguments and pass them to the CLI

---

packages/custom-webpack/package.json
packages/jest/src/index.ts

Fix jest cli issue

---

.github/ISSUE_TEMPLATE/bug_report.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: update issue template to force providing reproduction

---

.travis.yml
package.json
scripts/local-registry.sh
scripts/verdaccio.yaml

```
[ ] Bugfix
[ ] Feature
[x ] CI related changes
```
```
[ ] Yes
[x] No
```

ci: cleanup

---

packages/jest/README.md

docs: Fix broken link using relative path for default-config.ts
[ x ] Documentation content changes

docs: Fix broken link using relative

---

packages/jest/src/jest-config/global-mocks.ts

feat: mock matchMedia out of the box

---

packages/jest/package.json

```
[X] Bugfix
[ ] Feature
```
Closes #697 
```
[ ] Yes
[X] No
```

fix(jest): bump jest-preset-angular from 8.0.0 to 8.1.2

---

packages/custom-webpack/examples/full-cycle-app/package.json
packages/custom-webpack/examples/sanity-app/package.json
packages/jest/examples/multiple-apps/package.json
packages/jest/examples/simple-app/package.json
packages/timestamp/example/package.json

```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
Use Angular Devkit 0.100x.0
```
[ ] Yes
[x] No
```

chore: update dependencies

---

packages/custom-webpack/CHANGELOG.md
packages/custom-webpack/README.md
packages/custom-webpack/package.json
packages/jest/CHANGELOG.md
packages/jest/package.json
packages/timestamp/CHANGELOG.md
packages/timestamp/package.json

```
[ ] Bugfix
[ ] Feature
```
Links in CHANGELOGs are broken.
Closes #800
Links are valid
```
[ ] Yes
[x] No
```

Fix CHANGELOG links

---

.all-contributorsrc
README.md

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
I have changed my username from `jsone-studios` to `sonallux`. This PR changes all references in the contributors' section from my old username to the new one.
```
[ ] Yes
[x] No
```

docs: change username of contributor

---

packages/custom-webpack/README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(custom-webpack): fix mergeRules prepend example

---

.github/workflows/ci.yml

```
[ ] Bugfix
[ ] Feature
```
The CI process use cache v1
Use the cache v2 to take benefits of new features listed [here](https://github.com/actions/cache)
```
[ ] Yes
[x] No
```

upgrade to actions/cache@v2 and actions/setup-node@v2

---

packages/custom-webpack/src/custom-webpack-builder.ts
packages/custom-webpack/src/schemes.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #924 
A quick fix just in order to be able to release new versions by updating schemes file. 
A proper fix should be implemented in a separate PR.
```
[ ] Yes
[x] No
```

Add schemes stamp

---

packages/custom-webpack/README.md

Missing builder in custom webpack readme
Added extract-i18n to available builder in the angular.json example file.

Added extract-i18n to available builders

---

packages/jest/src/schema.json

```
[x] Bugfix
[ ] Feature
```
Issue Number: closes #969 
`maxWorkers` accepts both `string` and `number` 
```
[ ] Yes
[x] No
```

fix(jest): correct maxWorkers type

---

MIGRATION.MD
README.md
packages/custom-webpack/README.md
packages/jest/README.md

```
[ ] Bugfix
[ ] Feature
```

docs: update docs to match v12

---

packages/jest/README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(doc): Add snippet block on the README

---

packages/custom-webpack/README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Chore: fix typo

---

packages/jest/src/schema.json

```
[x] Bugfix
[ ] Feature
```
Issue Number: closes #1032 
`no-cache` option is acceptable
```
[ ] Yes
[x] No
```

fix(jest): accept no-cache option

---

MIGRATION.MD
README.md
packages/custom-webpack/README.md
packages/jest/README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: update docs to match v13

---

packages/jest/package.json

For my project, rc1 wasn't working.
It seems 11 has released. we could use that?
I don't think much needs to be updated?
```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe: Dependecy updates
```
```
[ ] Yes
[x ] No
```

Set jest-preset-angular to non rc version

---

packages/jest/README.md
packages/jest/examples/multiple-apps/tsconfig.base.json
packages/jest/scripts/ci.sh
packages/jest/src/schema.json

```
[x] Bugfix
[ ] Feature
```
Fixes #1065 
The schema is fixed and `find-related-tests` now accepts multiple parameters
```
[ ] Yes
[x] No
```

fix(jest): find-related-tests schema and e2e

---

examples/custom-webpack/full-cycle-app/angular.json
examples/custom-webpack/sanity-app/angular.json
examples/jest/multiple-apps/angular.json
examples/jest/simple-app/angular.json
examples/timestamp/angular.json

```
[ ] Bugfix
[ ] Feature
```
Cypress uses its default browser (Electron) which requires xvbf and sometimes causes errors when running multiple instances
Cypress uses Chrome 
```
[ ] Yes
[x] No
```

ci: use chrome browser for Cypress

---

scripts/run-ci.sh

```
[ ] Bugfix
[ ] Feature
```
`Xvfb` server is started by Cypress for each instance
`Xvfb` server is started once by `run-ci.sh`
```
[ ] Yes
[x] No
```

ci: start Xvfb for Cypress

---

packages/jest/src/schema.json

```
[x] Bugfix
[ ] Feature
```
Fixes #1236, fixes #1247

fix: remove conflicting commands and aliases

---

packages/jest/scripts/ci.sh
packages/jest/src/schema.json

```
[x] Bugfix
[ ] Feature
```
`ng test --no-cache` is throwing an error when using Jest Builder.
`ng test --no-cache` works as expected
```
[ ] Yes
[x] No
```
Fixes #1247 , related to #1281

fix: jest no-cache option

---

examples/bazel/package.json
examples/custom-webpack/full-cycle-app/package.json
examples/custom-webpack/sanity-app-esm/package.json
examples/custom-webpack/sanity-app/package.json
examples/jest/multiple-apps/package.json
examples/jest/simple-app/package.json
examples/timestamp/package.json
package.json
scripts/run-ci.sh
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
- Use `worspace:*` for all examples to ensure the local version of packages is used
- Use `lerna-lite` instead of `lerna` (the latter doesn't support `workspace:*` protocol)
```
[ ] Yes
[x] No
```

build: use workspace protocol for examples

---

packages/custom-webpack/README.md

fixed README
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Fixed README.md

---

packages/custom-webpack/README.md
packages/custom-webpack/e2e/custom-webpack-config-schema.ts
packages/custom-webpack/src/custom-webpack-builder-config.ts
packages/custom-webpack/src/custom-webpack-builder.spec.ts
packages/custom-webpack/src/custom-webpack-builder.ts
packages/custom-webpack/src/schema.ext.json

This is a follow-up PR of the #633, since it's never been updated after and I just forgot about it. I'l mark it as a draft for now just to wait for your comments.

feat(custom-webpack): provide `verbose` option

---

examples/jest/simple-app/src/app/app.component.html
examples/jest/simple-app/src/app/app.component.spec.ts
examples/jest/simple-app/src/app/app.module.ts
examples/jest/simple-app/src/app/link/link.component.html
examples/jest/simple-app/src/app/link/link.component.spec.ts
examples/jest/simple-app/src/app/link/link.component.ts
packages/jest/scripts/ci.sh

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: add test shard two parts
```
```
[ ] Yes
[x] No
```

test(jest): add test shard 1/2 and 2/2 and suites skipped

---

examples/jest/simple-app/angular.json
examples/jest/simple-app/jest.config.mjs
examples/jest/simple-app/jest.config.ts
examples/jest/simple-app/package.json
package.json
packages/jest/README.md
packages/jest/package.json
packages/jest/scripts/ci.sh
packages/jest/src/custom-config.resolver.spec.ts
packages/jest/src/custom-config.resolver.ts
packages/jest/src/default-config.resolver.spec.ts
packages/jest/src/default-config.resolver.ts
packages/jest/src/index.ts
packages/jest/src/jest-configuration-builder.spec.ts
packages/jest/src/jest-configuration-builder.ts
packages/jest/src/types.ts
packages/jest/src/utils.ts
yarn.lock

feat(jest): support Jest config in different formats

---

packages/jest/README.md

- [ x Tests for the changes have been added (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1333
More clarity on global mocks.
```
[ ] Yes
[x] No
```

docs: Add more detail about global mocks for jsdom (#1333)

---

packages/custom-webpack/README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Make the sentence more clear

---

packages/custom-esbuild/src/schemes.ts

```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: Schema update
```
```
[ ] Yes
[x] No
```
Schema for `custom-webpack` is generated during the build based on the base schema from Angular CLI. This PR bumps the base schema to include changes from `17.3.2`.  
Closes #1728

chore(custom-webpack): update base schemes
